name: Simple Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  silly-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run reusable silly check action
        uses: ./.github/actions/silly-check
        with:
          file-to-check: README.md
